### ISSUE TITLE
When I import a png image, it apparently blurred than the origin one, how to handle it? 

### ISSUE THREAD

**Issue by cyberpsyche** [w00dn/papergrapher#2]
I tried a bunch of png files to import them into the papergrapher, but apparently every png image will be sort of blurred or compressed someway other than the original ones. Even the sizes of the images remain the same , the resolutions or dpi became worse. I wonder what is the cause of this problem, and how to handle it? 

I hope to use the exact resolution of the images when import them into papergrapher. 

Thanks a lot !

**Comment by w00dn** [comment]
Hmm, I can't reproduce this problem. It works fine on my end. Even with 300dpi png files and transparency.

![mario](https://user-images.githubusercontent.com/8849160/109931638-62099d00-7cc9-11eb-86ec-e836a4080777.PNG)
